/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as crowdFundingMultiSol from "./CrowdFundingMulti.sol";
export { CrowdFunding__factory } from "./CrowdFunding__factory";
export { MyToken__factory } from "./MyToken__factory";
