/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as crowdFundingMultiSol from "./CrowdFundingMulti.sol";
export type { crowdFundingMultiSol };
export type { CrowdFunding } from "./CrowdFunding";
export type { MyToken } from "./MyToken";
